version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:
        - CMD-SHELL
        - |
          curl -s http://localhost:9200/_cluster/health | grep -q '"status":"\(green\|yellow\)"'
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
