// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/chr1sbest/hybrid-search/pkg/storage"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, query, topK
func (_m *Service) Search(ctx context.Context, query string, topK int) ([]storage.Document, error) {
	ret := _m.Called(ctx, query, topK)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []storage.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]storage.Document, error)); ok {
		return rf(ctx, query, topK)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []storage.Document); ok {
		r0 = rf(ctx, query, topK)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, topK)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
