openapi: 3.0.0
info:
  title: Hybrid Search API
  version: 1.0.0
  description: A simple API for storing and querying documents using a hybrid search system.

paths:
  /store:
    post:
      summary: Store a new document
      operationId: StoreDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreRequest'
      responses:
        '201':
          description: Document stored successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /query:
    get:
      summary: Query for documents
      operationId: QueryDocuments
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: The search query text.
      responses:
        '200':
          description: A list of search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: Missing query parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    StoreRequest:
      type: object
      properties:
        text:
          type: string
          description: The text content of the document to store.
      required:
        - text

    Document:
      type: object
      properties:
        document_id:
          type: string
        parent_document_id:
          type: string
        text:
          type: string

    SuccessMessage:
      type: object
      properties:
        message:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
